<?php

declare(strict_types=1);

namespace ItaliaMultimedia\XPayWeb\Enum;

/**
 * @see https://developer.nexi.it/en/altro-/codifiche/codici-errore
 */
enum NexiErrorCode: string
{
    case GENERIC_API_ERROR = 'PS0000';
    case PAYPAL_CANCEL_NOT_ALLOWED = 'PS0001';
    case CANCEL_ONLY_SAME_DAY = 'PS0002';
    case CARD_VERIFICATION_ERROR = 'PS0004';
    case INVALID_INSTALLMENT_AMOUNT = 'PS0005';
    case INVALID_INSTALLMENT_DATE = 'PS0006';
    case PAYMENT_SESSION_AMOUNT_TOO_HIGH = 'PS0007';
    case INVALID_REQUESTED_DATE = 'PS0008';
    case INVALID_CURRENCY = 'PS0009';
    case INVALID_REQUESTED_DATE_ALT = 'PS0010';
    case INVALID_TIME_FORMAT = 'PS0011';
    case INVALID_TIME_RANGE = 'PS0012';
    case INVALID_DATE_RANGE = 'PS0013';
    case INVALID_CONTRACT_ID = 'PS0017';
    case CONTRACT_RETRIEVE_ERROR = 'PS0018';
    case ALREADY_CAPTURED_OPERATION = 'PS0022';
    case ALREADY_EXECUTED_OPERATION = 'PS0023';
    case ALREADY_REFUNDED_CAPTURE = 'PS0024';
    case IDEMPOTENCY_KEY_MISSING_OR_INVALID = 'PS0025';
    case INVALID_PARAMETER = 'PS0026';
    case OPERATION_ALREADY_REFUNDED = 'PS0027';
    case OPERATION_ALREADY_VOIDED = 'PS0028';
    case REFUND_AMOUNT_TOO_HIGH = 'PS0029';
    case PAYPAL_VOID_ERROR = 'PS0032';
    case PAYPAL_REFUND_ERROR = 'PS0033';
    case PAYPAL_CAPTURE_ERROR = 'PS0034';
    case JSON_PROCESSING_ERROR = 'PS0035';
    case INVALID_ORDER_AMOUNT = 'PS0036';
    case TENANT_MERCHANT_TERMINAL_MISSING = 'PS0040';
    case EMBEDDED_JAVASCRIPT_FORBIDDEN = 'PS0041';
    case PAY_BY_LINK_VALIDATION_ERROR = 'PS0042';
    case MIT_INVOCATION_ERROR = 'PS0043';
    case PAYMENT_LINK_DELETE_ERROR = 'PS0044';
    case PAYMENT_LINK_ALREADY_USED = 'PS0045';
    case PAYMENT_METHOD_TERMINAL_NOT_FOUND = 'PS0051';
    case INVALID_TERMINAL_ID = 'PS0052';

    case MERCHANT_URL_INVALID = 'GW0001';
    case FIELD_CONFIGURATION_INVALID = 'GW0002';
    case LANGUAGE_CONFIGURATION_INVALID = 'GW0003';
    case PAYMENT_SESSION_NOT_FOUND = 'GW0004';
    case INVALID_JWT_CLAIMS = 'GW0005';
    case VALUE_NOT_FOUND = 'GW0006';
    case ORDER_NOT_FOUND = 'GW0007';
    case OPERATION_NOT_ALLOWED = 'GW0008';
    case OPERATION_NOT_ALLOWED_IN_CURRENT_STATE = 'GW0009';
    case INVALID_PAYMENT_STATE = 'GW0010';
    case INVALID_PAYMENT_METHOD = 'GW0011';
    case INVALID_TEXT_FIELD = 'GW0012';
    case TEXT_FIELD_CONFIGURATION_INCOMPLETE = 'GW0013';
    case INVALID_ACTION_CONFIGURATION = 'GW0014';
    case PAYMENT_SETUP_FAILED_CARD_DATA = 'GW0015';
    case PAYMENT_SETUP_INTERNAL_ERROR = 'GW0016';
    case DUPLICATE_OPERATION = 'GW0017';
    case ORDER_ID_MISSING = 'GW0018';
    case ORDER_AMOUNT_INVALID = 'GW0019';
    case INSTALLMENT_AMOUNT_INVALID = 'GW0020';
    case AMOUNT_LITERAL_INVALID = 'GW0021';
    case LANGUAGE_FORMAT_INVALID = 'GW0022';
    case CUSTOMER_ID_MISSING = 'GW0023';
    case DUPLICATE_ORDER = 'GW0024';
    case MERCHANT_NOT_ENABLED_FOR_APM = 'GW0025';
    case TERMINAL_NOT_FOUND = 'GW0026';
    case PAYMENT_REST_COMMUNICATION_ERROR = 'GW0027';
    case ORDER_RECURRING_INFO_NOT_FOUND = 'GW0028';
    case ORDER_RECURRING_INFO_RETRIEVE_ERROR = 'GW0029';
    case INVALID_GDI_URL = 'GW0030';
    case AUTHORIZATION_BEARER_INVALID = 'GW0031';
    case PAYMENT_VALIDATION_INTERNAL_ERROR = 'GW0032';
    case ORDER_OPERATION_NOT_FOUND = 'GW0033';
    case PAYMENT_INTERNAL_ERROR = 'GW0034';
    case INTERNAL_ERROR = 'GW0035';
    case API_NOT_ALLOWED_WITH_APM = 'GW0036';
    case CARD_VALUES_REQUIRED = 'GW0037';
    case SERVICE_TEMPORARILY_UNAVAILABLE = 'GW0038';
    case INVALID_APM = 'GW0039';
    case INVALID_FIELD = 'GW0040';
    case HOSTED_LOG_NOT_FOUND = 'GW0041';
    case TRANSACTION_NOT_FOUND = 'GW0042';
    case ORDER_REQUIREMENTS_NOT_MET = 'GW0043';
    case TERMINAL_MULTI_ACQUIRING_GROUP_MISMATCH = 'GW0044';
}
